var wpi = require('wiring-pi');

// GPIO pin of the led
//var configPin = 3;
// Blinking interval in usec
var configTimeout = 100;

wpi.setup('wpi');
//wpi.pinMode( 1, wpi.OUTPUT);
//wpi.pinMode( 2, wpi.OUTPUT);
wpi.pinMode( 3, wpi.OUTPUT);
//wpi.pinMode( 4, wpi.OUTPUT);
wpi.pinMode( 5, wpi.OUTPUT);
//wpi.pinMode( 6, wpi.OUTPUT);
wpi.pinMode( 7, wpi.OUTPUT);
wpi.pinMode( 8, wpi.OUTPUT);
//wpi.pinMode( 9, wpi.OUTPUT);
wpi.pinMode(10, wpi.OUTPUT);
wpi.pinMode(11, wpi.OUTPUT);
wpi.pinMode(12, wpi.OUTPUT);
wpi.pinMode(13, wpi.OUTPUT);
//wpi.pinMode(14, wpi.OUTPUT);
wpi.pinMode(15, wpi.OUTPUT);
wpi.pinMode(16, wpi.OUTPUT);
//wpi.pinMode(17, wpi.OUTPUT);
wpi.pinMode(18, wpi.OUTPUT);
wpi.pinMode(19, wpi.OUTPUT);
//wpi.pinMode(20, wpi.OUTPUT);
wpi.pinMode(21, wpi.OUTPUT);
wpi.pinMode(22, wpi.OUTPUT);
wpi.pinMode(23, wpi.OUTPUT);
wpi.pinMode(24, wpi.OUTPUT);
//wpi.pinMode(25, wpi.OUTPUT);
wpi.pinMode(26, wpi.OUTPUT);
wpi.pinMode(27, wpi.OUTPUT);
wpi.pinMode(28, wpi.OUTPUT);
wpi.pinMode(29, wpi.OUTPUT);
//wpi.pinMode(30, wpi.OUTPUT);
wpi.pinMode(31, wpi.OUTPUT);
wpi.pinMode(32, wpi.OUTPUT);
wpi.pinMode(33, wpi.OUTPUT);
//wpi.pinMode(34, wpi.OUTPUT);
wpi.pinMode(35, wpi.OUTPUT);
wpi.pinMode(36, wpi.OUTPUT);
wpi.pinMode(37, wpi.OUTPUT);
wpi.pinMode(38, wpi.OUTPUT);
//wpi.pinMode(39, wpi.OUTPUT);
wpi.pinMode(40, wpi.OUTPUT);

var isLedOn = 0;

setInterval(function() {
	isLedOn = +!isLedOn;
	//isLedOn = !isLedOn;
	//wpi.digitalWrite(configPin, isLedOn );
        //wpi.digitalWrite( 1, isLedOn);
        //wpi.digitalWrite( 2, isLedOn);
        wpi.digitalWrite( 3, isLedOn);
	//wpi.digitalWrite( 4, isLedOn);
        wpi.digitalWrite( 5, isLedOn);
        //wpi.digitalWrite( 6, isLedOn);
        wpi.digitalWrite( 7, isLedOn);
        wpi.digitalWrite( 8, isLedOn);
        //wpi.digitalWrite( 9, isLedOn);
        wpi.digitalWrite(10, isLedOn);
        wpi.digitalWrite(11, isLedOn);
        wpi.digitalWrite(12, isLedOn);
        wpi.digitalWrite(13, isLedOn);
        //wpi.digitalWrite(14, isLedOn);
        wpi.digitalWrite(15, isLedOn);
        wpi.digitalWrite(16, isLedOn);
        //wpi.digitalWrite(17, isLedOn);
        wpi.digitalWrite(18, isLedOn);
        wpi.digitalWrite(19, isLedOn);
        //wpi.digitalWrite(20, isLedOn);
        wpi.digitalWrite(21, isLedOn);
        wpi.digitalWrite(22, isLedOn);
        wpi.digitalWrite(23, isLedOn);
        wpi.digitalWrite(24, isLedOn);
        //wpi.digitalWrite(25, isLedOn);
        wpi.digitalWrite(26, isLedOn);
        wpi.digitalWrite(27, isLedOn);
        wpi.digitalWrite(28, isLedOn);
        wpi.digitalWrite(29, isLedOn);
        //wpi.digitalWrite(30, isLedOn);
        wpi.digitalWrite(31, isLedOn);
        wpi.digitalWrite(32, isLedOn);
        wpi.digitalWrite(33, isLedOn);
        //wpi.digitalWrite(34, isLedOn);
        wpi.digitalWrite(35, isLedOn);
        wpi.digitalWrite(36, isLedOn);
        wpi.digitalWrite(37, isLedOn);
        wpi.digitalWrite(38, isLedOn);
        //wpi.digitalWrite(39, isLedOn);
        wpi.digitalWrite(40, isLedOn);
}, configTimeout);
